# Generated by Django 4.1.7 on 2023-03-14 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=150)),
                ('profile_image_url', models.CharField(default='No URL Provided', max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='OpenaiSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkoutapi.openaisuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkoutapi.checkoutuser')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('image_url', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkoutapi.checkoutuser')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default='No Date and Time Selected')),
                ('progress', models.BooleanField()),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkoutapi.cleaner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkoutapi.property')),
            ],
        ),
    ]
