# Generated by Django 4.1.7 on 2023-03-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(),
        ),
    ]
