# Generated by Django 4.1.7 on 2023-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapi', '0002_alter_property_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
