# Generated by Django 4.1.7 on 2023-03-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapi', '0003_alter_property_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningappointment',
            name='progress',
            field=models.BooleanField(default=False),
        ),
    ]
